version: '3.8'

services:
  # 后端服务
  backend:
    build: ./backend
    image: etf-assistant-backend:latest
    container_name: etf-assistant-backend
    volumes:
      - ./backend/.env:/app/.env:ro
    restart: unless-stopped

  # 前端服务
  frontend:
    build: ./frontend
    image: etf-assistant-frontend:latest
    container_name: etf-assistant-frontend
    depends_on:
      - backend
    ports:
      - "8123:80"
    restart: unless-stopped
